# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
#Мирзоян Виктория
import numpy as np
a=np.zeros(100)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [2]:
a=np.ones(100)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [3]:
a=np.full(100,3)
a

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [4]:
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [5]:
a=np.arange(16).reshape(4,4)
print(a)
a[[0,1]]=a[[1,0]]
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 6. Создать вектор со значениями от 10 до 100

In [6]:
a=np.arange(10,101)
a

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [7]:
b=np.arange(20)
print(b)
b=b[::-1]
b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [8]:
a=np.arange(16).reshape(4,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [9]:
b=np.arange(1,6)
print(b)
c=np.zeros(17)
c[::4]=b
c


[1 2 3 4 5]


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [10]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [11]:
a=np.random.random((3,3,3))
a

array([[[0.97037389, 0.97585732, 0.87712725],
        [0.20055812, 0.83713264, 0.56856429],
        [0.32743271, 0.05785559, 0.82740435]],

       [[0.68095287, 0.55115706, 0.65214797],
        [0.12081781, 0.9071953 , 0.51320429],
        [0.30082775, 0.21437255, 0.84370762]],

       [[0.31244011, 0.66820975, 0.9577595 ],
        [0.64701055, 0.21548633, 0.98967021],
        [0.23211445, 0.42121722, 0.88821137]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [12]:
a=np.random.random((10,10))
print(a)
print(a.min(),a.max())

[[0.65135652 0.73593754 0.32402485 0.73871475 0.43019759 0.59204684
  0.39671897 0.11449601 0.08860857 0.97177995]
 [0.42304539 0.63329369 0.84257089 0.66563617 0.05168438 0.84997138
  0.48658012 0.40566514 0.76411335 0.43957998]
 [0.66070189 0.46385294 0.15904721 0.83239415 0.87020711 0.58525645
  0.2795562  0.43185681 0.53146322 0.78682624]
 [0.29621151 0.45302992 0.7647857  0.87223618 0.58515566 0.5587554
  0.79350718 0.35278058 0.03911938 0.49011555]
 [0.44475544 0.92312057 0.5686575  0.40385321 0.61131013 0.81206252
  0.65714392 0.16961965 0.3438341  0.78631801]
 [0.08453945 0.62648056 0.97838808 0.25332832 0.26232339 0.79159021
  0.9688422  0.37896291 0.60134075 0.92246229]
 [0.30149216 0.74622112 0.46972466 0.7078404  0.72785244 0.60231836
  0.91729446 0.50410261 0.21734678 0.8541258 ]
 [0.94297068 0.26444808 0.48339119 0.25077777 0.13625984 0.47580712
  0.9840524  0.95472709 0.48205061 0.28617419]
 [0.4839113  0.17989058 0.66879428 0.61133806 0.68156799 0.50168797
  0.48452802 

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [13]:
a=np.random.random((30))
a.mean()

0.5433506748930739

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [14]:
a=np.ones((4,4))
a[1:3,1:3]=0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 15. Выяснить результат следующих выражений

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [15]:
a=np.diag(np.array([1, 2, 2, 4, 0]))
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [16]:
b=np.zeros((8,8))
b[1::2,1::2]=1
b[::2,::2]=1
b

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [17]:
a=numpy.unravel_index(100,(6,7,8))
a

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [18]:
a=np.tile(np.array([[1,0],[0,1]]),(4,4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [19]:
a=np.random.random(15).reshape(5,3)
b=np.random.random(6).reshape(3,2)
print(a)
print(b)
c=np.dot(a,b)
c

[[0.64596514 0.63028738 0.38472706]
 [0.22835988 0.92511447 0.97974365]
 [0.04432971 0.54670145 0.05530351]
 [0.20372056 0.16108201 0.39172948]
 [0.04943203 0.52871656 0.2891119 ]]
[[0.59441372 0.5140521 ]
 [0.57430544 0.58939057]
 [0.96490852 0.07038984]]


array([[1.11717443, 0.73062605],
       [1.61240151, 0.73160662],
       [0.39368663, 0.34890126],
       [0.59158768, 0.22723697],
       [0.61199441, 0.35738173]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [20]:
a=np.random.random(10)
a[4:8]*=-1
a

array([ 0.15338781,  0.90306652,  0.45754423,  0.9348804 , -0.10297727,
       -0.58890134, -0.2465482 , -0.50048427,  0.44005253,  0.32496274])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [21]:
a=np.zeros((5,5))
b=np.arange(5)
a=a+b
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 24. Есть генератор, сделать с его помощью массив

In [26]:
def generator():
    for a in range(10):
        yield a
b=np.fromiter(generator(),dtype=int)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [130]:
a=np.linspace(0,1,10,endpoint=False)[1::]
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 26. Отсортировать вектор

In [132]:
a=np.random.random(5)
print(a)
a.sort()
a

[0.67531867 0.07769948 0.06448268 0.90000023 0.0728275 ]


array([0.06448268, 0.0728275 , 0.07769948, 0.67531867, 0.90000023])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [136]:
a=np.random.random(5)
b=np.random.random(5)
np.allclose(a,b)

False

#### 28. Сделать массив неизменяемым

In [29]:
a=tuple(np.random.random(5))
a

(0.14799924852594526,
 0.7999853442602981,
 0.8398100582808774,
 0.5264693283701524,
 0.7583698293842357)

#### 29. Найти n наибольших значений в массиве

In [37]:
a=np.random.random(10)
a.sort()
n=4
print(a)
a[len(a)-1:len(a)-n-1:-1]

[0.07281254 0.08397338 0.34198262 0.38680473 0.42563681 0.48472137
 0.52443263 0.61846339 0.68124629 0.97741535]


array([0.97741535, 0.68124629, 0.61846339, 0.52443263])

#### 30. Заменить максимальный элемент на ноль

In [40]:
a=np.random.random(10)
print(a)
a[np.argmax(a)]=0
print(a)

[0.01665466 0.63542002 0.07106069 0.21706502 0.15776859 0.14565495
 0.62802687 0.28500423 0.61440442 0.49352456]
[0.01665466 0.         0.07106069 0.21706502 0.15776859 0.14565495
 0.62802687 0.28500423 0.61440442 0.49352456]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [7]:
x=np.arange(10)
y=np.array([11,12,13,14])
x=x.reshape((-1,1))
c=x-y
d=1.0/c
d

[0 1 2 3 4 5 6 7 8 9]


array([[-0.09090909, -0.08333333, -0.07692308, -0.07142857],
       [-0.1       , -0.09090909, -0.08333333, -0.07692308],
       [-0.11111111, -0.1       , -0.09090909, -0.08333333],
       [-0.125     , -0.11111111, -0.1       , -0.09090909],
       [-0.14285714, -0.125     , -0.11111111, -0.1       ],
       [-0.16666667, -0.14285714, -0.125     , -0.11111111],
       [-0.2       , -0.16666667, -0.14285714, -0.125     ],
       [-0.25      , -0.2       , -0.16666667, -0.14285714],
       [-0.33333333, -0.25      , -0.2       , -0.16666667],
       [-0.5       , -0.33333333, -0.25      , -0.2       ]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [8]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [11]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [19]:
a=np.arange(10)
print(a)
n=2.71828
print(n)
c=(np.abs(a-n)).argmin()
print(a[c])


[0 1 2 3 4 5 6 7 8 9]
2.71828
3


#### 36. Преобразовать массив из float в int

In [20]:
a=np.arange(10, dtype=np.int32)
a=a.astype(np.float32, copy=False)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [22]:
#np.ndenumerate()
a=np.array([[1, 2, 4], [3, 4, 8]])
for y, x in np.ndenumerate(a):
    print(y, x)

(0, 0) 1
(0, 1) 2
(0, 2) 4
(1, 0) 3
(1, 1) 4
(1, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [30]:
a=np.ones((6,6))
np.put(a, np.random.choice(range(36), 4, replace=False), 0)
a

array([[1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 39. Отнять среднее из каждой строки в матрице

In [35]:
a=np.random.rand(2, 3)
print(a)
print(a.mean())
a-a.mean()

[[0.06596842 0.05249853 0.80264295]
 [0.37646407 0.07054242 0.70921604]]
0.34622207302553315


array([[-0.28025365, -0.29372354,  0.45642088],
       [ 0.030242  , -0.27567965,  0.36299397]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [40]:
a=np.random.randint(10,100,(5,5))
print(a)
print(a[a[:,4].argsort()])

[[81 50 77 14 36]
 [14 34 94 96 86]
 [54 92 55 81 58]
 [72 80 33 21 35]
 [33 29 68 25 30]]
[[33 29 68 25 30]
 [72 80 33 21 35]
 [81 50 77 14 36]
 [54 92 55 81 58]
 [14 34 94 96 86]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [44]:
a=np.random.randint(0,10,(10,10))
print(a)
print((~a.any(axis=0)).any())

[[4 9 3 9 2 0 1 9 7 5]
 [2 5 5 4 8 4 5 2 9 4]
 [6 4 0 0 0 9 4 6 5 0]
 [5 1 9 4 5 5 9 4 5 3]
 [4 0 5 1 7 4 2 6 2 1]
 [9 4 2 3 5 8 8 2 9 6]
 [0 7 1 6 7 5 7 1 7 7]
 [2 5 7 5 9 4 8 7 4 4]
 [5 9 6 2 7 8 0 0 2 9]
 [6 6 6 1 1 5 7 7 9 3]]
False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [51]:
a=np.ones(20)
print(a)
b=np.random.randint(0,len(a),len(a))
print(b)
a+=np.bincount(b, minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[17 18 18  8  3 11  5 17 17 12 10  8  7  0  1 15  4  7  0 19]
[3. 2. 1. 2. 2. 2. 1. 3. 3. 1. 2. 2. 2. 1. 1. 2. 1. 4. 3. 2.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [69]:
a=np.random.randint(0,100,(4,4,4,4))
print(a)
a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)

[[[[53 31 26 82]
   [ 6 89 90 53]
   [87 80 11  8]
   [ 1 88 37 44]]

  [[37  3  9 87]
   [64 47 24 28]
   [80 51 41 43]
   [99 79 96 13]]

  [[10 50 99 44]
   [51  0 31 56]
   [42 17  9 88]
   [63 20 87 11]]

  [[10 74 14 94]
   [36 11 26 62]
   [43 67 56 34]
   [48 99 23 94]]]


 [[[62 19 30 75]
   [43 41 41 70]
   [ 4 44 21 16]
   [57 95 41 37]]

  [[63 83 27 33]
   [34 50 92 38]
   [83 73 97 97]
   [26 14 28 15]]

  [[18 53 89 62]
   [57 56  4 68]
   [ 1 73 84  5]
   [10 56 69 32]]

  [[ 0 28 10 56]
   [46 45 89 86]
   [93 18  2 30]
   [29 99 66 55]]]


 [[[99 32 13 10]
   [97 57 15  5]
   [88 86 68 49]
   [63 85 31 13]]

  [[ 6 46 20 96]
   [15 99 48 59]
   [38 74 18 39]
   [51 79 72 56]]

  [[56 18 94 60]
   [ 3 52 63  4]
   [ 3 50 71 35]
   [10 93  1 76]]

  [[ 2  4 40 38]
   [87 48 59  0]
   [14 32 29 95]
   [11 85 83  7]]]


 [[[75 20 29 75]
   [ 7 72 44 95]
   [86 98 88 11]
   [82 77  1 95]]

  [[75  0 11 58]
   [ 2 33 62 15]
   [39  9 14 53]
   [57 79 31 99]]

  [[84 89 55 2

array([[786, 801, 678, 791],
       [696, 853, 737, 752],
       [811, 816, 689, 634],
       [955, 637, 774, 611]])